### ISSUE TITLE
wiki: complete the data science example

### ISSUE THREAD

**Issue by ivotron** [getpopper/popper#12]
- [x] Add link(s) to 'Intro to Popper' once it's done (see #6)
- [x] Add link to 'Tool agnosticism' once it's done (see #6)
- [x] Add link to '.popper.yml config' once it's done (see #11)
- [x] Add link to 'Folder Structure' explanation once it's done (see 
  #10)
- [x] Add description of BWW notebook (what it consists off) 
- [x] Finish with 'Adding More Datasets' section
- [x] Finish 'Generating Image Files for Later Usage' section
- [x] Finish 'Documenting Experiment' section
